### ISSUE TITLE
Bug: Bot says playing a new file when one is already playing

### ISSUE THREAD

**Issue by RDardelet** [romainisnel/Music-Bot#3]
Small bug report

The bot will always say it's playing a newly pasted soundcloud file when it's already playing a file.

A simple error message should do the trick.

**Comment by romainisnel** [comment]
This will be fixed in 0.6.1

**Comment by romainisnel** [comment]
Fixed in [ddaa889](https://github.com/romainisnel/Music-Bot/commit/6896479f26cd056adf5bcd52ce0071fd512cacb1)
