### ISSUE TITLE
Suggestion: Print message for direct file play

### ISSUE THREAD

**Issue by RDardelet** [romainisnel/Music-Bot#4]
Let's also print a message when we paste a direct music file

Like  *>Playing [a-Z|0-9].mp3 from the web.*

**Comment by romainisnel** [comment]
This will be implemented on the 0.6.1 version

**Comment by romainisnel** [comment]
Done in [84e1f20](https://github.com/romainisnel/Music-Bot/commit/caa02f585de312f7725eec9f5daf699e755e0b1d)
